version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "45432:5432"
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
  web:
    build: .
    volumes:
      - ./apps:/apps
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
    working_dir: /apps
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev}
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST:-db}
      RAILS_ENV: ${RAILS_ENV:-development}