default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: <%= ENV['POSTGRES_DB_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: apps_test

production:
  <<: *default
  database: asahikodb
